name: GitHub NPM Test

on:
  push:
    branches-ignore:
      - 'dependabot/**'
      - trunk
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Dependencies
        run: bun install --frozen-lockfile --ignore-scripts

      - name: Run Markdownlint
        run: bun run lint:md

      - name: Run ESLint
        run: bun run lint:js

      - name: Run cSpell
        run: |
          echo "::add-matcher::.github/workflows/cspell-problem-matcher.json"
          bun run lint:spell

      - name: Run tests
        run: bun test

      - name: Build container
        run: |
          docker build .
