name: NIH GHMP Container (Prod) - Build & Register

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'jobs/**'
      - 'business/**'
      - 'lib/**'
      - 'config/**'
      - 'interfaces/**'
      - 'package.json'
      - 'bun.lock'
      - 'tsconfig.json'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: get orgs from graphql
        run: |
          gh api graphql -f ent=nih -f query='query($ent: String!) {
            enterprise(slug: $ent) {
              organizations(first: 100) {
                nodes {
                  description
                  login
                  databaseId
                  id
                  name
                }
              }
            }
          }' >> raw.json
          cat raw.json
        env:
          GITHUB_TOKEN: ${{ secrets.ENT_READ_PAT}}
      - name: run powershell script to create env orgs json
        run: |
          ./.github/scripts/Create-EnvOrgs.ps1
          cat orgs.json
          ls
        shell: pwsh
      - name: check file
        run: |
          cat orgs.json
          ls -lah
          rm env-orgs.json
          cat orgs.json >> env-orgs.json
          cat env-orgs.json
      - uses: azure/docker-login@15c4aadf093404726ab2ff205b2cdd33fa6d054c # v2
        with:
          login-server: ${{ secrets.PROD_REGISTRY_SERVER }}
          username: ${{ secrets.PROD_REGISTRY_USER }}
          password: ${{ secrets.PROD_REGISTRY_PASS }}
      - run: |
          docker build . -t ${{ secrets.PROD_REGISTRY_SERVER }}/portal
          docker push ${{ secrets.PROD_REGISTRY_SERVER }}/portal
