name: NIH GHMP Container (Dev) - Build & Register

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: azure/docker-login@v2
      with:
        login-server: ${{ secrets.DEV_REGISTRY_SERVER }}
        username: ${{ secrets.DEV_REGISTRY_USER }}
        password: ${{ secrets.DEV_REGISTRY_PASS }}
    - run: |
        docker build . -t ${{ secrets.DEV_REGISTRY_SERVER }}/portal
        docker push ${{ secrets.DEV_REGISTRY_SERVER }}/portal
